name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Upload for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: linux
          - os: macos-latest
            target: macos
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build binary
        run: cargo build --release --all-features

      - name: Extract version
        id: extract_version
        run: |
          version=$(cargo metadata --format-version 1 --no-deps | jq -r ".packages[0].version")
          echo "version=$version" >> "$GITHUB_OUTPUT"
